In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:2]

array([1])

In [7]:
arr[:5
   ]

array([0, 1, 2, 3, 4])

In [8]:
arr[0:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr_copy = arr.copy()

In [11]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(1,11)

In [13]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [15]:
bool_arr = arr > 5

In [16]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [17]:
arr [bool_arr]

array([ 6,  7,  8,  9, 10])

In [18]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr_2d = np.arange(1,51).reshape(5,10)

In [20]:
arr_2d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [22]:
arr_2d[3][2:5]

array([33, 34, 35])

In [23]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [28]:
import numpy as np


In [27]:
import pandas as pd

In [29]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

In [31]:
pd.Series(data = my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [32]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [33]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [35]:
ser1 = pd.Series([1,2,3,4],['USA','Brazil','Canada','Mexico'])

In [36]:
ser1

USA       1
Brazil    2
Canada    3
Mexico    4
dtype: int64

In [37]:
ser1['USA']

1

In [38]:
from numpy.random import randn

In [39]:
np.random.seed(101
            )

In [40]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [41]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [42]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [43]:
type(df['W'])

pandas.core.series.Series

In [45]:
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [46]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [47]:
df['new'] = df['W'] + df['Y']

In [48]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [52]:
df.drop('new',axis=1,inplace=True)

In [51]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [53]:
df.drop('E')

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [54]:
df.shape

(5, 4)

In [55]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [56]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [57]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [59]:
df.loc['B','Y']

-0.8480769834036315

In [60]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [61]:
df > 0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [62]:
booldf = df > 0


In [64]:
df[booldf]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [70]:
resultdf = df[df['W']>0]

In [68]:
df['W']>0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [69]:
df[df['Z']<0]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [71]:
resultdf['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [75]:
df[df['W']>0][['X','Y']]

X         Y
A  0.628133  0.907969
B -0.319318 -0.848077
D -0.758872 -0.933237
E  1.978757  2.605967

In [76]:
boolser = df['W']>0
result = df[boolser]
result[['X','Y']]

X         Y
A  0.628133  0.907969
B -0.319318 -0.848077
D -0.758872 -0.933237
E  1.978757  2.605967

In [78]:
df[(df['W']>0) & (df['Y']>1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [79]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [80]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [81]:
newind = 'CA MY WY OR CD'.split()

In [82]:
newind

['CA', 'MY', 'WY', 'OR', 'CD']

In [83]:
df['States'] = newind

In [85]:
df.set_index ('States')

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
MY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CD      0.190794  1.978757  2.605967  0.683509

In [86]:
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     MY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CD