In [6]:
lst = [x**2 for x in range(1,10)]

In [4]:
lst


[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [5]:
import numpy as np

In [7]:
arr = np.array(lst)

In [8]:
arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.random.rand(5)

array([0.63324366, 0.11495675, 0.72183046, 0.9853355 , 0.52096938])

In [12]:
np.random.rand(5,5)

array([[0.83943373, 0.60420088, 0.32762074, 0.97676089, 0.16842217],
       [0.46250781, 0.2503921 , 0.48619859, 0.97543697, 0.69650913],
       [0.22464393, 0.79508793, 0.70443358, 0.31136013, 0.54149594],
       [0.95050159, 0.74029672, 0.77174043, 0.09872464, 0.40989722],
       [0.63703636, 0.86500975, 0.42130884, 0.26191913, 0.27302005]])

In [13]:
np.random.randn(2)

array([0.40510382, 1.65946879])

In [15]:
np.random.randint(1,100,10
                )

array([78, 64, 22, 78, 33,  4, 69, 22, 45, 66])

In [22]:
arr2 = np.arange(25)

In [23]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
arr2.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr = np.random.randint(1,25,10)

In [31]:
ranarr

array([16, 18,  8, 16,  3, 19, 19, 15, 12, 10])

In [32]:
ranarr.min()

3

In [33]:
ranarr.argmin()

4

In [34]:
ranarr[4]

3

In [36]:
ranarr.shape

(10,)

In [37]:
ranarr.dtype

dtype('int32')